### ISSUE TITLE
can we not depend on plyr?

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint#49]
I made a viz with geom_step (whose conversion uses ddply) and I got this error

```
Error in saveLayer(L, df, meta) : could not find function "ddply"
Calls: animint2dir -> parsePlot -> saveLayer
```

**Comment by cpsievert** [comment]
It's my understanding that you should avoid DEPENDS at all costs since it loads that package into the global NAMESPACE. In my opinion, plyr should be in IMPORTS for this reason. The problem is that, even though plyr appears under IMPORTS in the DESCRIPTION file, it doesn't currently appear in the NAMESPACE file, so it won't be made available to internal package functions.

A quick fix would be to just add `#' @import plyr` and re-`document()` which would add `import(plyr)` to the NAMESPACE. 

A more careful fix would be to add `plyr::` to any plyr functions, such as [this line](https://github.com/tdhock/animint/blob/master/R/animint.R#L1058). I would prefer this approach [since **plyr** functions are known to clash with **dplyr**](https://github.com/hadley/dplyr#plyr-compatibility)

**Comment by tdhock** [comment]
plyr:: sounds like a good quick fix

**Comment by cpsievert** [comment]
Just discovered this neat little function for discovering this type of problem:

```r
codetools::checkUsagePackage("animint", all = TRUE)
```
